### ISSUE TITLE
PHP 7.4 support for Magento 2.3.x (v1.0.1)

### ISSUE THREAD

**Issue by mamsincl** [MonogoPolska/monogo-m2-disable-customer-log#1]
Hi Guys,

Can we get a PHP 7.4 compatible package which supports Magento 2.3.7, please?

**Comment by pawel-detka** [comment]
Hi @mamsincl 
Version 1.0.1 is no longer supported and not tested with PHP7.4 but you can try to install it with
```--ignore-platform-reqs``` switch

**Comment by mamsincl** [comment]
Hi Pavel,

Sadly as CI/CD, our deployment pipeline cannot run with this switch ... so move the module to _app/code_ then ...

Thanks,
R.

**Comment by pawel-detka** [comment]
Thank you

**Comment by mamsincl** [comment]
an idea from me:

https://github.com/MonogoPolska/monogo-m2-disable-customer-log/blob/master/composer.json#L7

can you check if it is compatible with 102.0.7  ... at least having something for latest M2.3.7 with php7.4
